- label: "JIRA"
  message: "$issuePrefix"
  color: "blue"
  url: "https://compalswhq.atlassian.net/browse/$issuePrefix"
  when: "$issuePrefix"

- label: "🛑"
  message: "WIP"
  color: "yellow"
  when: "$payload.pull_request.title.includes('WIP')"
